name = "FLPAccumbensRaphe"
uuid = "0609f6ce-626f-4e91-8922-f5a1b955a37c"
authors = ["Dario"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
